# Generated by Django 3.2.8 on 2022-12-20 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liberia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='image',
            new_name='imagen',
        ),
    ]
